/* Generated By:JavaCC: Do not edit this line. DemoParserConstants.java */
package demo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DemoParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int DOUBLE = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int OPEN_PAR = 12;
  /** RegularExpression Id. */
  int CLOSE_PAR = 13;
  /** RegularExpression Id. */
  int OPEN_BRACE = 14;
  /** RegularExpression Id. */
  int CLOSE_BRACE = 15;
  /** RegularExpression Id. */
  int OPEN_SQUARE = 16;
  /** RegularExpression Id. */
  int CLOSE_SQUARE = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int ASSIGNMENT = 19;
  /** RegularExpression Id. */
  int LOGIC_EQUALITY = 20;
  /** RegularExpression Id. */
  int LOGIC_INEQUALITY = 21;
  /** RegularExpression Id. */
  int LOGIC_AND = 22;
  /** RegularExpression Id. */
  int LOGIC_OR = 23;
  /** RegularExpression Id. */
  int LESS_THAN = 24;
  /** RegularExpression Id. */
  int GREATER_THAN = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int COMA = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int ELSE = 29;
  /** RegularExpression Id. */
  int FOR = 30;
  /** RegularExpression Id. */
  int AS = 31;
  /** RegularExpression Id. */
  int END = 32;
  /** RegularExpression Id. */
  int VARIABLE = 33;
  /** RegularExpression Id. */
  int OTHER = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"double\"",
    "\"int\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<NUMBER>",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\";\"",
    "\",\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"as\"",
    "\"end\"",
    "<VARIABLE>",
    "<OTHER>",
  };

}
